### ISSUE TITLE
Could not resolve "./vuepress-theme"

### ISSUE THREAD

**Issue by ipkpjersi** [cfw-guide/dsi.cfw.guide#176]
I'm on NodeJS 16.18.1 with the latest master branch of this repo.

I did an npm install then npm run docs:dev but then I got the following error:

```
npm run docs:dev

> docs:dev
> vuepress dev docs

✘ [ERROR] Could not resolve "./vuepress-theme"

    docs/.vuepress/config.js:2:27:
      2 │ import { emiylTheme } from "./vuepress-theme";
        ╵                            ~~~~~~~~~~~~~~~~~~

Error: Build failed with 1 error:
docs/.vuepress/config.js:2:27: ERROR: Could not resolve "./vuepress-theme"
    at failureErrorWithLog (/home/user/Desktop/dsi.cfw.guide/node_modules/esbuild/lib/main.js:1651:15)
    at /home/user/Desktop/dsi.cfw.guide/node_modules/esbuild/lib/main.js:1059:25
    at runOnEndCallbacks (/home/user/Desktop/dsi.cfw.guide/node_modules/esbuild/lib/main.js:1486:45)
    at buildResponseToResult (/home/user/Desktop/dsi.cfw.guide/node_modules/esbuild/lib/main.js:1057:7)
    at /home/user/Desktop/dsi.cfw.guide/node_modules/esbuild/lib/main.js:1086:16
    at responseCallbacks.<computed> (/home/user/Desktop/dsi.cfw.guide/node_modules/esbuild/lib/main.js:704:9)
    at handleIncomingPacket (/home/user/Desktop/dsi.cfw.guide/node_modules/esbuild/lib/main.js:764:9)
    at Socket.readFromStdout (/home/user/Desktop/dsi.cfw.guide/node_modules/esbuild/lib/main.js:680:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
```

Any ideas of what might be going wrong?

**Comment by emiyl** [comment]
you must clone the repo recursively

**Comment by ipkpjersi** [comment]
Yep, that was it. Thanks!

**Comment by ipkpjersi** [comment]
@emiyl I just realized, I wonder if it might be worth mentioning in the README that the repo must be cloned recursively?
